ZayShopMVC/Areas/Admin/Models/Slider/SliderCommandVM.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ZayShopMVC.Areas.Admin.Models.Slider;

public class SliderCommandVM
{
    [Required(ErrorMessage = "Please enter title")]
    public string Title { get; set; }
    [Required(ErrorMessage = "Please enter subtitle")]
    public string Subtitle { get; set; }
    [Required(ErrorMessage = "Please enter description")]
    public string Description { get; set; }
    [Required(ErrorMessage = "Please enter image url")]
    public string ImageUrl { get; set; }

    [Required(ErrorMessage = "Please enter sort order")]
    [Range(1, int.MaxValue, ErrorMessage = "Sort order must be greater than 0")]
    public int SortOrder { get; set; }
}

ZayShopMVC/Areas/Admin/Models/Slider/SliderVM.cs
using System;
using E = ZayShopMVC.Data.Entities;

namespace ZayShopMVC.Areas.Admin.Models.Slider;

public class SliderVM
{
    public List<E.Slider> Sliders { get; set; }
}

ZayShopMVC/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using ZayShopMVC.Areas.Admin.Models.Slider;
using ZayShopMVC.Data;
using ZayShopMVC.Data.Entities;

namespace ZayShopMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        readonly AppDbContext _context;

        public SliderController(AppDbContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var model = new SliderVM
            {
                Sliders = _context.Sliders.ToList()
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SliderCommandVM model)
        {
            if (!ModelState.IsValid)
                return View();

            if (_context.Sliders.Any(s => s.SortOrder == model.SortOrder))
            {
                ModelState.AddModelError("SortOrder", "Order already exists");
                return View();
            }

            var slider = new Slider
            {
                Title = model.Title,
                Subtitle = model.Subtitle,
                Description = model.Description,
                ImageUrl = model.ImageUrl,
                SortOrder = model.SortOrder
            };

            _context.Sliders.Add(slider);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var slider = _context.Sliders.Find(id);

            if (slider == null)
                return NotFound();

            var model = new SliderCommandVM
            {
                Title = slider.Title,
                Subtitle = slider.Subtitle,
                Description = slider.Description,
                ImageUrl = slider.ImageUrl,
                SortOrder = slider.SortOrder
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(int id, SliderCommandVM model)
        {
            if (!ModelState.IsValid)
                return View();

            var slider = _context.Sliders.Find(id);

            if (slider == null)
                return NotFound();

            if (_context.Sliders.Any(s => s.SortOrder == model.SortOrder && s.Id != id))
            {
                ModelState.AddModelError("SortOrder", "Order already exists");
                return View();
            }

            slider.Title = model.Title;
            slider.Subtitle = model.Subtitle;
            slider.Description = model.Description;
            slider.ImageUrl = model.ImageUrl;
            slider.SortOrder = model.SortOrder;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var slider = _context.Sliders.Find(id);

            if (slider == null)
                return NotFound();

            _context.Sliders.Remove(slider);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

ZayShopMVC/Areas/Admin/Views/Slider/Create.cshtml
@using ZayShopMVC.Areas.Admin.Models.Slider
@model SliderCommandVM

<form asp-controller="Slider" asp-action="Create" method="post" class="p-4">
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Slider Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Subtitle" class="form-label">Subtitle</label>
        <input type="text" class="form-control" asp-for="Subtitle" placeholder="Slider Subtitle">
        <span asp-validation-for="Subtitle" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">Description</label>
        <textarea type="text" class="form-control" asp-for="Description" placeholder="Slider description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="ImageUrl" class="form-label">Image url</label>
        <input type="text" class="form-control" asp-for="ImageUrl" placeholder="Slider image">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="SortOrder" class="form-label">Sort order</label>
        <input type="number" class="form-control" asp-for="SortOrder" placeholder="Slider order" min="1">
        <span asp-validation-for="SortOrder" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

ZayShopMVC/Areas/Admin/Views/Slider/Index.cshtml
@using ZayShopMVC.Areas.Admin.Models.Slider
@model SliderVM

<div class="p-4">
    <a type="button" class="btn btn-primary mb-4" asp-controller="Slider" asp-action="Create">Create</a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Subtitle</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>
                <th scope="col">Sort Order</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Sliders)
            {
                <tr>
                    <td>@item.Title</td>
                    <td>@item.Subtitle</td>
                    <td>@item.Description</td>
                    <td>
                        <img src="~/@item.ImageUrl" alt="@item.Title" style="width: 100px; height: 100px;" />
                    </td>
                    <td>@item.SortOrder</td>
                    <td class="d-flex">
                        <a type="button" class="btn btn-primary mr-3" asp-controller="Slider" asp-action="Update"
                            asp-route-id="@item.Id">Update</a>
                        <form asp-controller="Slider" asp-action="Delete" asp-route-id="@item.Id" method="post">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ZayShopMVC/Areas/Admin/Views/Slider/Update.cshtml
@using ZayShopMVC.Areas.Admin.Models.Slider
@model SliderCommandVM

<form asp-controller="Slider" asp-action="Update" method="post" class="p-4">
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Slider Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Subtitle" class="form-label">Subtitle</label>
        <input type="text" class="form-control" asp-for="Subtitle" placeholder="Slider Subtitle">
        <span asp-validation-for="Subtitle" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">Description</label>
        <textarea type="text" class="form-control" asp-for="Description" placeholder="Slider description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="ImageUrl" class="form-label">Image url</label>
        <input type="text" class="form-control" asp-for="ImageUrl" placeholder="Slider image">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="SortOrder" class="form-label">Sort order</label>
        <input type="number" class="form-control" asp-for="SortOrder" placeholder="Slider order" min="1">
        <span asp-validation-for="SortOrder" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>